# Generated by Django 5.0.1 on 2024-02-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_storystream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
