# Generated by Django 5.0.1 on 2024-02-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_alter_story_expiration_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='expiration_time',
            new_name='posted',
        ),
    ]
