# Generated by Django 5.0.1 on 2024-01-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stream_comment_alter_follow_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='comment',
        ),
    ]
