# Generated by Django 5.0.1 on 2024-03-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='Authuser.userprofile'),
        ),
    ]
