# Generated by Django 5.0.1 on 2024-02-07 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_sender_message_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
            ],
        ),
    ]
